import pg from 'pg';
const { Client } = pg;

const client = new Client({
    connectionString: `postgresql://postgres.vhuvnutzklhskkwbpxdz:Srbr19010720%40@aws-0-sa-east-1.pooler.supabase.com:6543/postgres`,
    ssl: { rejectUnauthorized: false }
});

async function main() {
    await client.connect();
    console.log('✅ Conectado ao Supabase!');

    try {
        console.log('⏳ Criando tabela integracoes_meta...');
        await client.query(`
            CREATE TABLE IF NOT EXISTS public.integracoes_meta (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                organizacao_id BIGINT NOT NULL REFERENCES public.organizacoes(id) ON DELETE CASCADE ON UPDATE CASCADE,
                access_token TEXT NOT NULL,
                whatsapp_business_account_id TEXT NOT NULL,
                status TEXT DEFAULT 'ativo',
                created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
            );
        `);
        console.log('✅ Tabela integracoes_meta criada com sucesso!');

        console.log('⏳ Habilitando e Blindando RLS na tabela integracoes_meta...');
        await client.query(`
            ALTER TABLE public.integracoes_meta ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS "Leitura de integracoes_meta permitida" ON public.integracoes_meta;
            CREATE POLICY "Leitura de integracoes_meta permitida" ON public.integracoes_meta
                FOR SELECT TO authenticated
                USING (organizacao_id = get_auth_user_org() OR organizacao_id = 1);

            DROP POLICY IF EXISTS "Insercao de integracoes_meta permitida" ON public.integracoes_meta;
            CREATE POLICY "Insercao de integracoes_meta permitida" ON public.integracoes_meta
                FOR INSERT TO authenticated
                WITH CHECK (organizacao_id = get_auth_user_org() OR organizacao_id = 1);

            DROP POLICY IF EXISTS "Atualizacao de integracoes_meta permitida" ON public.integracoes_meta;
            CREATE POLICY "Atualizacao de integracoes_meta permitida" ON public.integracoes_meta
                FOR UPDATE TO authenticated
                USING (organizacao_id = get_auth_user_org() OR organizacao_id = 1);

            DROP POLICY IF EXISTS "Delecao de integracoes_meta permitida" ON public.integracoes_meta;
            CREATE POLICY "Delecao de integracoes_meta permitida" ON public.integracoes_meta
                FOR DELETE TO authenticated
                USING (organizacao_id = get_auth_user_org() OR organizacao_id = 1);
        `);
        console.log('✅ Blindagem RLS concluída em integracoes_meta!');

        console.log('⏳ Verificando estrutura de configuracoes_whatsapp...');
        
        // Garantir que configuracoes_whatsapp não tenha null na organizacao_id
        await client.query(`
            ALTER TABLE public.configuracoes_whatsapp ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS "Leitura configuracoes_whatsapp" ON public.configuracoes_whatsapp;
            CREATE POLICY "Leitura configuracoes_whatsapp" ON public.configuracoes_whatsapp
                FOR SELECT TO authenticated
                USING (organizacao_id = get_auth_user_org() OR organizacao_id = 1);

            DROP POLICY IF EXISTS "Insercao configuracoes_whatsapp" ON public.configuracoes_whatsapp;
            CREATE POLICY "Insercao configuracoes_whatsapp" ON public.configuracoes_whatsapp
                FOR INSERT TO authenticated
                WITH CHECK (organizacao_id = get_auth_user_org() OR organizacao_id = 1);

            DROP POLICY IF EXISTS "Atualizacao configuracoes_whatsapp" ON public.configuracoes_whatsapp;
            CREATE POLICY "Atualizacao configuracoes_whatsapp" ON public.configuracoes_whatsapp
                FOR UPDATE TO authenticated
                USING (organizacao_id = get_auth_user_org() OR organizacao_id = 1);

            DROP POLICY IF EXISTS "Delecao configuracoes_whatsapp" ON public.configuracoes_whatsapp;
            CREATE POLICY "Delecao configuracoes_whatsapp" ON public.configuracoes_whatsapp
                FOR DELETE TO authenticated
                USING (organizacao_id = get_auth_user_org() OR organizacao_id = 1);
        `);
        console.log('✅ Blindagem RLS concluída em configuracoes_whatsapp!');

    } catch(e) {
        console.error('❌ ERRO CRÍTICO:', e);
    } finally {
        await client.end();
        console.log('🔌 Conexão encerrada.');
    }
}

main();
